default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000

development:
  <<: *default
  host: localhost
  database: ash
  username: root
  password:

production:
  <<: *default
  host: localhost
  username: ash_p_user
  password: ydD331Ur177XB
  database: ash_production

staging:
  <<: *default
  host: localhost
  database: ash_staging
  username: ash_staging_user
  password: ftSdwa4w
