default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000

development:
  <<: *default
  host: localhost
  database: ash
  username: root
  password:

production:
  <<: *default
  host: localhost
  username: ash_p_user
  password: calculi72
  database: ash_production

staging:
  <<: *default
  host: localhost
  database: ash
  username: ash
  password: E#E0J1uQ0ZJX5s
